 
# Базовий образ з Python 3.12 + dev tools
FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye


COPY requirements.txt /tmp/requirements.txt
COPY app /app


# Встановлюємо Python-залежності
RUN pip install --no-cache-dir -r /tmp/requirements.txt
                                 
# Відкриваємо порт
EXPOSE 7004

CMD ["uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", "7004"]